version: '3.8'

volumes:
  prometheus_data:
    external: true

services:
  postgres:
    container_name: numerario_postgres
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=numerario_db

  prometheus:
    depends_on:
      - postgres
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
#      - prometheus_data:/prometheus
    networks:
      - gv-network
    ports:
      - "9090:9090"

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    networks:
      - gv-network
    ports:
      - "3000:3000"


networks:
  gv-network:
    driver: bridge